### ISSUE TITLE
Compile error - Attribute error

### ISSUE THREAD

**Issue by DrKunohara** [lux4rd0/homeassistant#5]
Good evening,

i tried to compile your fantastic Lilygo-Code under the most current esphome (version 2022.9.2) but it failed with the following error message:

INFO Reading configuration /config/esphome/lilygo_t5_weatherflow.yaml...
INFO Updating https://github.com/ashald/esphome.git@lilygo-t5-47
INFO Updating https://github.com/esphome/esphome.git@pull/3577/head
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING 'weatherflow_display': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
WARNING The selected Arduino framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 931, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 918, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/esphome/esphome/__main__.py", line 330, in command_compile
    exit_code = write_cpp(config)
  File "/esphome/esphome/__main__.py", line 163, in write_cpp
    generate_cpp_contents(config)
  File "/esphome/esphome/__main__.py", line 175, in generate_cpp_contents
    CORE.flush_tasks()
  File "/esphome/esphome/core/__init__.py", line 614, in flush_tasks
    self.event_loop.flush_tasks()
  File "/esphome/esphome/coroutine.py", line 245, in flush_tasks
    next(task.iterator)
  File "/esphome/esphome/__main__.py", line 155, in wrapped
    await coro(conf)
  File "/config/esphome/.esphome/external_components/c698a6f3/esphome/components/wifi/__init__.py", line 367, in to_code
    cg.with_local_variable(network[CONF_ID], WiFiAP(), add_sta, network)
AttributeError: module 'esphome.codegen' has no attribute 'with_local_variable'

Do you have any idea what to do?

**Comment by lux4rd0** [comment]
@DrKunohara Hello - and thanks for your message. I just compiled my esp instances for v2022.9.2, and I didn't get any errors. Let me grab an initial configuration for what I have listed and see if there's a difference. I've made so many changes to my displays, and I haven't updated much on Github. Did you make any specific changes? It looks like there's a conflict somewhere along the way not specific to my configs - but more the display driver/wifi driver. Did you clear your build cache just in case? I'll let you know what I find out.

**Comment by lux4rd0** [comment]
I'm now seeing this on a second esphome/HA instance and a different set of devices. I'll dig into this shortly.

**Comment by lux4rd0** [comment]
@DrKunohara, I'm curious if you're still seeing this. I'm no longer seeing it, but I've also updated a few of my configurations to work around multiple @ashald changes that impacted newer versions of esphome.
